#
# Azure Pipelines configuration for building and testing create-react-app on Linux, Windows, and macOS.
#

trigger:
- master

jobs:
- template: azure-pipelines-steps.yml
  parameters:
    jobName: Simple
    displayName: 'Simple'

- template: azure-pipelines-steps.yml
  parameters:
    jobName: Installs
    displayName: 'Installs'

- template: azure-pipelines-steps.yml
  parameters:
    jobName: KitchenSink
    displayName: 'Kitchen Sink'

- template: azure-pipelines-steps.yml
  parameters:
    jobName: KitchenSinkEject
    displayName: 'Kitchen Sink Eject'

- template: azure-pipelines-steps.yml
  parameters:
    jobName: OldNode
    displayName: 'Old Node'

- template: azure-pipelines-steps.yml
  parameters:
    jobName: Behavior
    displayName: 'Behavior'
