# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  node10_simple:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install
      - run: tasks/e2e-simple.sh
