version: 2

jobs:
  node10_simple:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install
      - run: sudo tasks/e2e-simple.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - node10_simple
